/**
 * Landing recordings manifest. GENERATED by scripts/landing-media/build-manifest.mjs
 * from the encoded renditions — do not edit by hand (run
 * `node scripts/landing-media/run-all.mjs`). URLs carry a content hash, so
 * /media/landing/* is served with `Cache-Control: immutable` (next.config.js).
 */
import type { MediaClip } from "./primitives/video-policy";

export const MEDIA = {
  "hero-overview": {
    id: "hero-overview",
    wide: {
      width: 1440,
      height: 900,
      light: {
        poster: "/media/landing/799ecbd4/hero-overview-light-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/hero-overview-light-960.webm",
            h264: "/media/landing/799ecbd4/hero-overview-light-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/hero-overview-light-1440.webm",
            h264: "/media/landing/799ecbd4/hero-overview-light-1440.mp4",
          },
        ],
      },
      dark: {
        poster: "/media/landing/799ecbd4/hero-overview-dark-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/hero-overview-dark-960.webm",
            h264: "/media/landing/799ecbd4/hero-overview-dark-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/hero-overview-dark-1440.webm",
            h264: "/media/landing/799ecbd4/hero-overview-dark-1440.mp4",
          },
        ],
      },
    },
  },
  "flow-catalog-import": {
    id: "flow-catalog-import",
    wide: {
      width: 1440,
      height: 900,
      light: {
        poster: "/media/landing/799ecbd4/flow-catalog-import-light-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-catalog-import-light-960.webm",
            h264: "/media/landing/799ecbd4/flow-catalog-import-light-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-catalog-import-light-1440.webm",
            h264: "/media/landing/799ecbd4/flow-catalog-import-light-1440.mp4",
          },
        ],
      },
      dark: {
        poster: "/media/landing/799ecbd4/flow-catalog-import-dark-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-catalog-import-dark-960.webm",
            h264: "/media/landing/799ecbd4/flow-catalog-import-dark-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-catalog-import-dark-1440.webm",
            h264: "/media/landing/799ecbd4/flow-catalog-import-dark-1440.mp4",
          },
        ],
      },
    },
  },
  "flow-container-ai": {
    id: "flow-container-ai",
    wide: {
      width: 1440,
      height: 900,
      light: {
        poster: "/media/landing/799ecbd4/flow-container-ai-light-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-container-ai-light-960.webm",
            h264: "/media/landing/799ecbd4/flow-container-ai-light-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-container-ai-light-1440.webm",
            h264: "/media/landing/799ecbd4/flow-container-ai-light-1440.mp4",
          },
        ],
      },
      dark: {
        poster: "/media/landing/799ecbd4/flow-container-ai-dark-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-container-ai-dark-960.webm",
            h264: "/media/landing/799ecbd4/flow-container-ai-dark-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-container-ai-dark-1440.webm",
            h264: "/media/landing/799ecbd4/flow-container-ai-dark-1440.mp4",
          },
        ],
      },
    },
  },
  "flow-orders-sale": {
    id: "flow-orders-sale",
    wide: {
      width: 1440,
      height: 900,
      light: {
        poster: "/media/landing/799ecbd4/flow-orders-sale-light-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-orders-sale-light-960.webm",
            h264: "/media/landing/799ecbd4/flow-orders-sale-light-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-orders-sale-light-1440.webm",
            h264: "/media/landing/799ecbd4/flow-orders-sale-light-1440.mp4",
          },
        ],
      },
      dark: {
        poster: "/media/landing/799ecbd4/flow-orders-sale-dark-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-orders-sale-dark-960.webm",
            h264: "/media/landing/799ecbd4/flow-orders-sale-dark-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-orders-sale-dark-1440.webm",
            h264: "/media/landing/799ecbd4/flow-orders-sale-dark-1440.mp4",
          },
        ],
      },
    },
  },
  "flow-receivables-close": {
    id: "flow-receivables-close",
    wide: {
      width: 1440,
      height: 900,
      light: {
        poster:
          "/media/landing/799ecbd4/flow-receivables-close-light-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-receivables-close-light-960.webm",
            h264: "/media/landing/799ecbd4/flow-receivables-close-light-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-receivables-close-light-1440.webm",
            h264: "/media/landing/799ecbd4/flow-receivables-close-light-1440.mp4",
          },
        ],
      },
      dark: {
        poster:
          "/media/landing/799ecbd4/flow-receivables-close-dark-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-receivables-close-dark-960.webm",
            h264: "/media/landing/799ecbd4/flow-receivables-close-dark-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-receivables-close-dark-1440.webm",
            h264: "/media/landing/799ecbd4/flow-receivables-close-dark-1440.mp4",
          },
        ],
      },
    },
  },
  "flow-inventory-stock": {
    id: "flow-inventory-stock",
    wide: {
      width: 1440,
      height: 900,
      light: {
        poster:
          "/media/landing/799ecbd4/flow-inventory-stock-light-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-inventory-stock-light-960.webm",
            h264: "/media/landing/799ecbd4/flow-inventory-stock-light-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-inventory-stock-light-1440.webm",
            h264: "/media/landing/799ecbd4/flow-inventory-stock-light-1440.mp4",
          },
        ],
      },
      dark: {
        poster: "/media/landing/799ecbd4/flow-inventory-stock-dark-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-inventory-stock-dark-960.webm",
            h264: "/media/landing/799ecbd4/flow-inventory-stock-dark-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-inventory-stock-dark-1440.webm",
            h264: "/media/landing/799ecbd4/flow-inventory-stock-dark-1440.mp4",
          },
        ],
      },
    },
  },
  "flow-rates-bcv": {
    id: "flow-rates-bcv",
    wide: {
      width: 1440,
      height: 900,
      light: {
        poster: "/media/landing/799ecbd4/flow-rates-bcv-light-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-rates-bcv-light-960.webm",
            h264: "/media/landing/799ecbd4/flow-rates-bcv-light-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-rates-bcv-light-1440.webm",
            h264: "/media/landing/799ecbd4/flow-rates-bcv-light-1440.mp4",
          },
        ],
      },
      dark: {
        poster: "/media/landing/799ecbd4/flow-rates-bcv-dark-poster.avif",
        videos: [
          {
            width: 960,
            av1: "/media/landing/799ecbd4/flow-rates-bcv-dark-960.webm",
            h264: "/media/landing/799ecbd4/flow-rates-bcv-dark-960.mp4",
          },
          {
            width: 1440,
            av1: "/media/landing/799ecbd4/flow-rates-bcv-dark-1440.webm",
            h264: "/media/landing/799ecbd4/flow-rates-bcv-dark-1440.mp4",
          },
        ],
      },
    },
  },
} as const satisfies Record<string, MediaClip>;

export type ClipId = keyof typeof MEDIA;
