/**
 * Landing media model and playback policy (PLAN-2026-09-LANDING-REDESIGN
 * §4.5). Pure: the manifest in `../media.ts` (generated by
 * scripts/landing-media) is typed with these interfaces, and `LandingVideo`
 * asks these functions what to load.
 */

export type MediaTheme = "light" | "dark";

/** One encoded width of a clip, in both codecs. */
export interface VideoRendition {
  width: number;
  /** AV1 in WebM — the primary source. */
  av1: string;
  /** H.264 in MP4 (faststart) — fallback for browsers without AV1. */
  h264: string;
}

export interface ThemedMedia {
  /** AVIF poster (last frame): what shows before and instead of the video. */
  poster: string;
  /** Sorted by width, ascending. */
  videos: readonly VideoRendition[];
}

export interface MediaFormat {
  width: number;
  height: number;
  light: ThemedMedia;
  dark: ThemedMedia;
}

export interface MediaClip {
  id: string;
  /** Desktop/tablet framing (16:10 app window). */
  wide: MediaFormat;
  /** Optional portrait recording for phones (< 768 px). */
  tall?: MediaFormat;
}

/** Codec string for `<source type>`: AV1 main profile, level 4.0, 8-bit. */
export const AV1_TYPE = 'video/webm; codecs="av01.0.08M.08"';
export const H264_TYPE = "video/mp4";

/** Screens are capped at 2× so a 3× phone never pulls the 1440 rendition. */
const MAX_DPR = 2;

/**
 * Smallest rendition that covers the rendered size at the device pixel
 * ratio; the largest one when none does.
 */
export function pickRendition(
  videos: readonly VideoRendition[],
  cssWidth: number,
  devicePixelRatio: number,
): VideoRendition | undefined {
  if (videos.length === 0) return undefined;
  const needed = cssWidth * Math.min(Math.max(devicePixelRatio, 1), MAX_DPR);
  const sorted = [...videos].sort((a, b) => a.width - b.width);
  return sorted.find((v) => v.width >= needed) ?? sorted[sorted.length - 1];
}

export interface PlaybackContext {
  prefersReducedMotion: boolean;
  /** `navigator.connection.saveData`, when the browser exposes it. */
  saveData: boolean;
}

/** Motion is decoration here: reduced motion or data saver → poster only. */
export function shouldPlayVideo(context: PlaybackContext): boolean {
  return !context.prefersReducedMotion && !context.saveData;
}

/** Portrait recording on phones when the clip has one. */
export function pickFormat(clip: MediaClip, isPhone: boolean): MediaFormat {
  return isPhone && clip.tall ? clip.tall : clip.wide;
}
