-- Rollback of 007_fk_covering_indexes.sql — drops exactly the 61 indexes it created.

BEGIN;

DROP INDEX IF EXISTS public.idx_account_receivable_order_id;
DROP INDEX IF EXISTS public.idx_account_receivable_workspace_id;
DROP INDEX IF EXISTS public.idx_approval_workspace_id;
DROP INDEX IF EXISTS public.idx_ar_installment_workspace_id;
DROP INDEX IF EXISTS public.idx_audit_log_workspace_id;
DROP INDEX IF EXISTS public.idx_cash_closure_workspace_id;
DROP INDEX IF EXISTS public.idx_category_alias_category_id;
DROP INDEX IF EXISTS public.idx_container_document_uploaded_by;
DROP INDEX IF EXISTS public.idx_container_document_workspace_id;
DROP INDEX IF EXISTS public.idx_container_item_suggested_product_id;
DROP INDEX IF EXISTS public.idx_container_item_workspace_id;
DROP INDEX IF EXISTS public.idx_customer_workspace_id;
DROP INDEX IF EXISTS public.idx_customer_address_workspace_id;
DROP INDEX IF EXISTS public.idx_delivery_note_created_by;
DROP INDEX IF EXISTS public.idx_delivery_note_item_workspace_id;
DROP INDEX IF EXISTS public.idx_exchange_rate_workspace_id;
DROP INDEX IF EXISTS public.idx_import_session_row_resolved_brand_id;
DROP INDEX IF EXISTS public.idx_import_session_row_resolved_category_id;
DROP INDEX IF EXISTS public.idx_import_session_row_resolved_product_id;
DROP INDEX IF EXISTS public.idx_import_session_row_workspace_id;
DROP INDEX IF EXISTS public.idx_integration_failure_resolved_by;
DROP INDEX IF EXISTS public.idx_integration_failure_workspace_id;
DROP INDEX IF EXISTS public.idx_integration_log_workspace_id;
DROP INDEX IF EXISTS public.idx_internal_invoice_created_by;
DROP INDEX IF EXISTS public.idx_internal_invoice_item_workspace_id;
DROP INDEX IF EXISTS public.idx_inventory_count_workspace_id;
DROP INDEX IF EXISTS public.idx_inventory_count_item_workspace_id;
DROP INDEX IF EXISTS public.idx_inventory_discrepancy_resolved_by;
DROP INDEX IF EXISTS public.idx_inventory_discrepancy_workspace_id;
DROP INDEX IF EXISTS public.idx_mercadolibre_order_event_workspace_id;
DROP INDEX IF EXISTS public.idx_ml_order_sales_order_id;
DROP INDEX IF EXISTS public.idx_notification_bucket_assignee_member_id;
DROP INDEX IF EXISTS public.idx_notification_bucket_assignee_workspace_id;
DROP INDEX IF EXISTS public.idx_notification_routing_rule_bucket_id;
DROP INDEX IF EXISTS public.idx_order_item_workspace_id;
DROP INDEX IF EXISTS public.idx_payment_workspace_id;
DROP INDEX IF EXISTS public.idx_payment_allocation_workspace_id;
DROP INDEX IF EXISTS public.idx_payment_evidence_uploaded_by;
DROP INDEX IF EXISTS public.idx_payment_evidence_workspace_id;
DROP INDEX IF EXISTS public.idx_price_history_workspace_id;
DROP INDEX IF EXISTS public.idx_pricing_rule_created_by;
DROP INDEX IF EXISTS public.idx_pricing_rule_workspace_id;
DROP INDEX IF EXISTS public.idx_product_uom_equivalence_workspace_id;
DROP INDEX IF EXISTS public.idx_quote_converted_order_id;
DROP INDEX IF EXISTS public.idx_quote_created_by;
DROP INDEX IF EXISTS public.idx_quote_item_workspace_id;
DROP INDEX IF EXISTS public.idx_repricing_event_workspace_id;
DROP INDEX IF EXISTS public.idx_role_permission_permission_id;
DROP INDEX IF EXISTS public.idx_sales_order_closed_by;
DROP INDEX IF EXISTS public.idx_sales_order_created_by;
DROP INDEX IF EXISTS public.idx_signature_workspace_id;
DROP INDEX IF EXISTS public.idx_stock_movement_warehouse_id;
DROP INDEX IF EXISTS public.idx_stock_movement_workspace_id;
DROP INDEX IF EXISTS public.idx_supplier_workspace_id;
DROP INDEX IF EXISTS public.idx_system_alert_workspace_id;
DROP INDEX IF EXISTS public.idx_user_profile_organization_id;
DROP INDEX IF EXISTS public.idx_vendor_commission_workspace_id;
DROP INDEX IF EXISTS public.idx_warehouse_workspace_id;
DROP INDEX IF EXISTS public.idx_workspace_created_by;
DROP INDEX IF EXISTS public.idx_workspace_member_invited_by;
DROP INDEX IF EXISTS public.idx_workspace_module_enabled_by;

COMMIT;
