/**
 * Film-grain tile for the product-frame backdrop (PLAN-2026-09-LANDING-REDESIGN
 * T2.4; reference: midday.ai's hero).
 *
 * A full-size grain image does not survive lossy compression (AVIF smooths
 * noise into a flat grey), so the backdrop is a CSS gradient built from theme
 * tokens with this small transparent noise tile repeated on top. One tile
 * serves both themes: black and white specks at low alpha.
 * Deterministic (seeded PRNG): the hash only changes when this script does.
 *
 * Writes apps/erp/public/media/landing/<hash8>/grain-tile.png and
 * apps/erp/src/app/_components/landing/grain.generated.ts.
 *
 * Run: node scripts/landing-media/build-grain.mjs
 */
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");
const ERP = join(ROOT, "apps/erp");
const sharp = createRequire(join(ERP, "package.json"))("sharp");

const SIZE = 128;
/** Peak speck opacity (0–255). */
const MAX_ALPHA = 34;
const MAX_BYTES = 30 * 1024;

function mulberry32(seed) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const random = mulberry32(7);
const rgba = Buffer.alloc(SIZE * SIZE * 4);
for (let i = 0; i < SIZE * SIZE; i++) {
  const value = random() < 0.5 ? 0 : 255;
  // Triangular distribution: most specks faint, a few stronger.
  const alpha = Math.round(Math.abs(random() + random() - 1) * MAX_ALPHA);
  rgba.set([value, value, value, alpha], i * 4);
}

const tile = await sharp(rgba, {
  raw: { width: SIZE, height: SIZE, channels: 4 },
})
  .png({ compressionLevel: 9, palette: true, colors: 64, effort: 10 })
  .toBuffer();
if (tile.length > MAX_BYTES) {
  throw new Error(`grain-tile.png is ${tile.length} B (> ${MAX_BYTES})`);
}

const hash = createHash("sha256").update(tile).digest("hex").slice(0, 8);
const dir = join(ERP, "public/media/landing", hash);
await mkdir(dir, { recursive: true });
await writeFile(join(dir, "grain-tile.png"), tile);

const path = `/media/landing/${hash}/grain-tile.png`;
console.log(`${path}: ${(tile.length / 1024).toFixed(1)} KB`);

await writeFile(
  join(ERP, "src/app/_components/landing/grain.generated.ts"),
  `// Generated by scripts/landing-media/build-grain.mjs — do not edit.\n` +
    `export const GRAIN_TILE = "${path}";\n` +
    `export const GRAIN_TILE_SIZE = ${SIZE};\n`,
);
